### PR TITLE
fixes #691

### LINKED ISSUE #691: `var x: seq[array[1, int]]` causes 'conflicting types' compile error from GCC
mytests/test.nim:
```nim
var x: seq[array[1, int]]
```

```console
$ ./bin/nimony c -r mytests/test.nim 
bin/nimsem  --isSystem m nimcache/sysvq0asl.1.nif nimcache/sysvq0asl.2.nif nimcache/sysvq0asl.2.idx.nif
bin/nimsem  m nimcache/tes9hvujc.1.nif nimcache/tes9hvujc.2.nif nimcache/tes9hvujc.2.idx.nif
cc -c   -Ivendor/mimalloc/include vendor/mimalloc/src/static.c -o nimcache/static.o
bin/hexer --bits:64 nimcache/tes9hvujc.2.nif
bin/nifc c --compileOnly --isMain  nimcache/tes9hvujc.c.nif
cc -c  -Imytests  nimcache/tes9hvujc.c -o nimcache/tes9hvujc.o
nimcache/tes9hvujc.c:325:1: error: conflicting types for ‘AarrayAiSminusQ1ZS1_0_t’; have ‘struct <anonymous>’
  325 | AarrayAiSminusQ1ZS1_0_t;
      | ^~~~~~~~~~~~~~~~~~~~~~~
nimcache/tes9hvujc.c:318:40: note: previous declaration of ‘AarrayAiSminusQ1ZS1_0_t’ with type ‘AarrayAiSminusQ1ZS1_0_t’
  318 | typedef struct AarrayAiSminusQ1ZS1_0_t AarrayAiSminusQ1ZS1_0_t;
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~
```

In generated C code, there are two typedef for `AarrayAiSminusQ1ZS1_0_t`.
```c
typedef struct AarrayAiSminusQ1ZS1_0_t AarrayAiSminusQ1ZS1_0_t;
typedef struct seq_0_tes9hvujc{
  NI len_0_tes9hvujc;
  AarrayAiSminusQ1ZS1_0_t* data_0_tes9hvujc;}
seq_0_tes9hvujc;
typedef struct {
  NI a[1];}
AarrayAiSminusQ1ZS1_0_t;
```

### PR DESCRIPTION
**Pull request by demotomohiro**
This PR produces code like this:
```c
typedef struct array array;
typedef struct seq{
  int len;
  array* data;}
seq;
typedef struct array {
  int a[1];}
array;
```

This compiles without error with gcc 14.2 and clang 19.1.0:
https://godbolt.org/z/5Yf3Wa6h8
https://godbolt.org/z/Yo19ba9c3

But fails to compile with gcc 4.5.3 and clang 3.5.2 and older:
https://godbolt.org/z/KWz8MG4ha
https://godbolt.org/z/Krq9Prjev

If it must be compiled without error with older gcc and clang, `array` must be defined without `typedef` if it is forward declared like this:
```c
typedef struct array array;
typedef struct seq{
  int len;
  array* data;}
seq;
struct array {
  int a[1];};
```
https://godbolt.org/z/dY9ncvYW4
https://godbolt.org/z/GfT6aK53a

Checking if it is forward declared and changing how to generate C array type definition would makes `src/nifc/gentypes.nim` more complicated.

### CODE REVIEW

File: src/nifc/gentypes.nim [hunk 1]
```diff
@@ -456,7 +456,6 @@ proc generateTypes(c: var GeneratedCode; o: TypeOrder) =
     let decl = takeTypeDecl(n)
     let s = mangle(pool.syms[decl.name.symId])
     c.add declKeyword
-    c.add "Q1_"
```
Comment (metagn) [inline src/nifc/gentypes.nim:459]: Does it break anything to keep these?
